import { Template } from "./types";

export const templates: Template[] = [
  // ============================================
  // PROFESSIONAL TEMPLATES (6)
  // ============================================
  {
    id: "classic-professional",
    name: "Classic Professional",
    nameRo: "Clasic Profesional",
    category: "professional",
    description: "Timeless design trusted by Fortune 500 companies",
    descriptionRo: "Design atemporal de încredere pentru companiile Fortune 500",
    layout: "single-column",
    colorScheme: {
      primary: "#1a365d",
      secondary: "#2d3748",
      accent: "#3182ce",
      background: "#ffffff",
      text: "#1a202c",
      muted: "#718096",
    },
    atsScore: 98,
    isPremium: false,
    previewImage: "/templates/classic-professional.png",
    tags: ["corporate", "traditional", "banking", "consulting"],
  },
  {
    id: "corporate-edge",
    name: "Corporate Edge",
    nameRo: "Corporate Edge",
    category: "professional",
    description: "Sharp and authoritative for business leaders",
    descriptionRo: "Clar și autoritar pentru lideri de business",
    layout: "sidebar-left",
    colorScheme: {
      primary: "#1e3a5f",
      secondary: "#34495e",
      accent: "#2980b9",
      background: "#ffffff",
      text: "#2c3e50",
      muted: "#7f8c8d",
    },
    atsScore: 95,
    isPremium: true,
    previewImage: "/templates/corporate-edge.png",
    tags: ["business", "finance", "management"],
  },
  {
    id: "wall-street",
    name: "Wall Street",
    nameRo: "Wall Street",
    category: "professional",
    description: "Refined elegance for finance professionals",
    descriptionRo: "Eleganță rafinată pentru profesioniști în finanțe",
    layout: "single-column",
    colorScheme: {
      primary: "#0d2137",
      secondary: "#1a3a5c",
      accent: "#c9a227",
      background: "#ffffff",
      text: "#1a202c",
      muted: "#64748b",
    },
    atsScore: 97,
    isPremium: true,
    previewImage: "/templates/wall-street.png",
    tags: ["finance", "investment", "banking", "luxury"],
  },
  {
    id: "consultant-pro",
    name: "Consultant Pro",
    nameRo: "Consultant Pro",
    category: "professional",
    description: "Strategic layout for consulting professionals",
    descriptionRo: "Layout strategic pentru profesioniști în consulting",
    layout: "two-column",
    colorScheme: {
      primary: "#1f2937",
      secondary: "#374151",
      accent: "#059669",
      background: "#ffffff",
      text: "#111827",
      muted: "#6b7280",
    },
    atsScore: 94,
    isPremium: true,
    previewImage: "/templates/consultant-pro.png",
    tags: ["consulting", "strategy", "management"],
  },
  {
    id: "legal-brief",
    name: "Legal Brief",
    nameRo: "Legal Brief",
    category: "professional",
    description: "Formal and precise for legal professionals",
    descriptionRo: "Formal și precis pentru profesioniști în domeniul juridic",
    layout: "single-column",
    colorScheme: {
      primary: "#1c1c1c",
      secondary: "#333333",
      accent: "#8b0000",
      background: "#ffffff",
      text: "#1a1a1a",
      muted: "#666666",
    },
    atsScore: 99,
    isPremium: false,
    previewImage: "/templates/legal-brief.png",
    tags: ["legal", "law", "attorney", "formal"],
  },
  {
    id: "healthcare-pro",
    name: "Healthcare Professional",
    nameRo: "Profesionist Sănătate",
    category: "professional",
    description: "Clean design for medical and healthcare careers",
    descriptionRo: "Design curat pentru cariere medicale și sănătate",
    layout: "sidebar-right",
    colorScheme: {
      primary: "#0891b2",
      secondary: "#155e75",
      accent: "#06b6d4",
      background: "#ffffff",
      text: "#164e63",
      muted: "#67e8f9",
    },
    atsScore: 96,
    isPremium: true,
    previewImage: "/templates/healthcare-pro.png",
    tags: ["medical", "healthcare", "nursing", "doctor"],
  },

  // ============================================
  // MODERN TEMPLATES (6)
  // ============================================
  {
    id: "tech-forward",
    name: "Tech Forward",
    nameRo: "Tech Forward",
    category: "modern",
    description: "Cutting-edge design for tech innovators",
    descriptionRo: "Design de ultimă oră pentru inovatori tech",
    layout: "sidebar-left",
    colorScheme: {
      primary: "#6366f1",
      secondary: "#4f46e5",
      accent: "#8b5cf6",
      background: "#fafafa",
      text: "#1e1b4b",
      muted: "#a5b4fc",
    },
    atsScore: 92,
    isPremium: false,
    previewImage: "/templates/tech-forward.png",
    tags: ["tech", "software", "developer", "startup"],
  },
  {
    id: "silicon-valley",
    name: "Silicon Valley",
    nameRo: "Silicon Valley",
    category: "modern",
    description: "Inspired by leading tech companies",
    descriptionRo: "Inspirat de companiile tech de top",
    layout: "two-column",
    colorScheme: {
      primary: "#0f172a",
      secondary: "#1e293b",
      accent: "#3b82f6",
      background: "#ffffff",
      text: "#0f172a",
      muted: "#94a3b8",
    },
    atsScore: 93,
    isPremium: true,
    previewImage: "/templates/silicon-valley.png",
    tags: ["tech", "engineer", "product", "startup"],
  },
  {
    id: "digital-native",
    name: "Digital Native",
    nameRo: "Digital Native",
    category: "modern",
    description: "Fresh design for digital professionals",
    descriptionRo: "Design fresh pentru profesioniști digitali",
    layout: "sidebar-right",
    colorScheme: {
      primary: "#7c3aed",
      secondary: "#5b21b6",
      accent: "#a78bfa",
      background: "#faf5ff",
      text: "#4c1d95",
      muted: "#c4b5fd",
    },
    atsScore: 90,
    isPremium: true,
    previewImage: "/templates/digital-native.png",
    tags: ["digital", "marketing", "social media", "content"],
  },
  {
    id: "startup-founder",
    name: "Startup Founder",
    nameRo: "Fondator Startup",
    category: "modern",
    description: "Dynamic layout for entrepreneurs",
    descriptionRo: "Layout dinamic pentru antreprenori",
    layout: "single-column",
    colorScheme: {
      primary: "#ea580c",
      secondary: "#c2410c",
      accent: "#fb923c",
      background: "#ffffff",
      text: "#1c1917",
      muted: "#a8a29e",
    },
    atsScore: 88,
    isPremium: true,
    previewImage: "/templates/startup-founder.png",
    tags: ["startup", "entrepreneur", "founder", "business"],
  },
  {
    id: "product-designer",
    name: "Product Designer",
    nameRo: "Designer Produs",
    category: "modern",
    description: "Showcase your UX/UI expertise",
    descriptionRo: "Evidențiază expertiza ta UX/UI",
    layout: "sidebar-left",
    colorScheme: {
      primary: "#ec4899",
      secondary: "#be185d",
      accent: "#f472b6",
      background: "#fdf2f8",
      text: "#831843",
      muted: "#f9a8d4",
    },
    atsScore: 85,
    isPremium: true,
    previewImage: "/templates/product-designer.png",
    tags: ["design", "UX", "UI", "product"],
  },
  {
    id: "data-scientist",
    name: "Data Scientist",
    nameRo: "Data Scientist",
    category: "modern",
    description: "Analytical layout for data professionals",
    descriptionRo: "Layout analitic pentru profesioniști în date",
    layout: "two-column",
    colorScheme: {
      primary: "#0d9488",
      secondary: "#0f766e",
      accent: "#2dd4bf",
      background: "#f0fdfa",
      text: "#134e4a",
      muted: "#99f6e4",
    },
    atsScore: 94,
    isPremium: false,
    previewImage: "/templates/data-scientist.png",
    tags: ["data", "analytics", "machine learning", "AI"],
  },

  // ============================================
  // CREATIVE TEMPLATES (5)
  // ============================================
  {
    id: "creative-studio",
    name: "Creative Studio",
    nameRo: "Studio Creativ",
    category: "creative",
    description: "Bold design for creative professionals",
    descriptionRo: "Design îndrăzneț pentru profesioniști creativi",
    layout: "sidebar-left",
    colorScheme: {
      primary: "#f43f5e",
      secondary: "#e11d48",
      accent: "#fda4af",
      background: "#fff1f2",
      text: "#881337",
      muted: "#fecdd3",
    },
    atsScore: 78,
    isPremium: true,
    previewImage: "/templates/creative-studio.png",
    tags: ["creative", "art", "design", "visual"],
  },
  {
    id: "portfolio-style",
    name: "Portfolio Style",
    nameRo: "Stil Portofoliu",
    category: "creative",
    description: "Visual-first layout for artists",
    descriptionRo: "Layout vizual pentru artiști",
    layout: "two-column",
    colorScheme: {
      primary: "#f59e0b",
      secondary: "#d97706",
      accent: "#fbbf24",
      background: "#fffbeb",
      text: "#78350f",
      muted: "#fde68a",
    },
    atsScore: 75,
    isPremium: true,
    previewImage: "/templates/portfolio-style.png",
    tags: ["portfolio", "artist", "photographer", "creative"],
  },
  {
    id: "media-maven",
    name: "Media Maven",
    nameRo: "Expert Media",
    category: "creative",
    description: "Dynamic design for media professionals",
    descriptionRo: "Design dinamic pentru profesioniști media",
    layout: "sidebar-right",
    colorScheme: {
      primary: "#dc2626",
      secondary: "#b91c1c",
      accent: "#fca5a5",
      background: "#fef2f2",
      text: "#7f1d1d",
      muted: "#fecaca",
    },
    atsScore: 80,
    isPremium: false,
    previewImage: "/templates/media-maven.png",
    tags: ["media", "journalism", "broadcasting", "content"],
  },
  {
    id: "fashion-forward",
    name: "Fashion Forward",
    nameRo: "Fashion Forward",
    category: "creative",
    description: "Stylish design for fashion industry",
    descriptionRo: "Design stilat pentru industria fashion",
    layout: "single-column",
    colorScheme: {
      primary: "#171717",
      secondary: "#262626",
      accent: "#d4d4d4",
      background: "#fafafa",
      text: "#0a0a0a",
      muted: "#a3a3a3",
    },
    atsScore: 82,
    isPremium: true,
    previewImage: "/templates/fashion-forward.png",
    tags: ["fashion", "style", "luxury", "retail"],
  },
  {
    id: "graphic-designer",
    name: "Graphic Designer",
    nameRo: "Designer Grafic",
    category: "creative",
    description: "Vibrant layout for visual designers",
    descriptionRo: "Layout vibrant pentru designeri vizuali",
    layout: "sidebar-left",
    colorScheme: {
      primary: "#8b5cf6",
      secondary: "#7c3aed",
      accent: "#c4b5fd",
      background: "#f5f3ff",
      text: "#5b21b6",
      muted: "#ddd6fe",
    },
    atsScore: 77,
    isPremium: true,
    previewImage: "/templates/graphic-designer.png",
    tags: ["graphic", "design", "illustration", "visual"],
  },

  // ============================================
  // MINIMALIST TEMPLATES (5)
  // ============================================
  {
    id: "clean-slate",
    name: "Clean Slate",
    nameRo: "Pagină Curată",
    category: "minimalist",
    description: "Pure simplicity with maximum impact",
    descriptionRo: "Simplitate pură cu impact maxim",
    layout: "single-column",
    colorScheme: {
      primary: "#18181b",
      secondary: "#27272a",
      accent: "#52525b",
      background: "#ffffff",
      text: "#09090b",
      muted: "#a1a1aa",
    },
    atsScore: 99,
    isPremium: false,
    previewImage: "/templates/clean-slate.png",
    tags: ["minimal", "clean", "simple", "elegant"],
  },
  {
    id: "nordic-simple",
    name: "Nordic Simple",
    nameRo: "Nordic Simplu",
    category: "minimalist",
    description: "Scandinavian-inspired clean design",
    descriptionRo: "Design curat inspirat scandinav",
    layout: "two-column",
    colorScheme: {
      primary: "#374151",
      secondary: "#4b5563",
      accent: "#9ca3af",
      background: "#f9fafb",
      text: "#1f2937",
      muted: "#d1d5db",
    },
    atsScore: 97,
    isPremium: true,
    previewImage: "/templates/nordic-simple.png",
    tags: ["nordic", "scandinavian", "clean", "light"],
  },
  {
    id: "zen-master",
    name: "Zen Master",
    nameRo: "Maestru Zen",
    category: "minimalist",
    description: "Balanced and harmonious layout",
    descriptionRo: "Layout echilibrat și armonios",
    layout: "single-column",
    colorScheme: {
      primary: "#44403c",
      secondary: "#57534e",
      accent: "#a8a29e",
      background: "#fafaf9",
      text: "#1c1917",
      muted: "#d6d3d1",
    },
    atsScore: 98,
    isPremium: false,
    previewImage: "/templates/zen-master.png",
    tags: ["zen", "calm", "balanced", "peaceful"],
  },
  {
    id: "swiss-design",
    name: "Swiss Design",
    nameRo: "Design Elvețian",
    category: "minimalist",
    description: "Typography-focused precision",
    descriptionRo: "Precizie focusată pe tipografie",
    layout: "sidebar-left",
    colorScheme: {
      primary: "#dc2626",
      secondary: "#1f2937",
      accent: "#ef4444",
      background: "#ffffff",
      text: "#111827",
      muted: "#9ca3af",
    },
    atsScore: 96,
    isPremium: true,
    previewImage: "/templates/swiss-design.png",
    tags: ["swiss", "typography", "grid", "precise"],
  },
  {
    id: "whitespace",
    name: "Whitespace",
    nameRo: "Spațiu Alb",
    category: "minimalist",
    description: "Breathing room for your content",
    descriptionRo: "Spațiu de respirație pentru conținut",
    layout: "single-column",
    colorScheme: {
      primary: "#0f172a",
      secondary: "#1e293b",
      accent: "#64748b",
      background: "#ffffff",
      text: "#0f172a",
      muted: "#cbd5e1",
    },
    atsScore: 99,
    isPremium: false,
    previewImage: "/templates/whitespace.png",
    tags: ["white", "space", "airy", "open"],
  },

  // ============================================
  // EXECUTIVE TEMPLATES (4)
  // ============================================
  {
    id: "ceo-suite",
    name: "CEO Suite",
    nameRo: "Suită CEO",
    category: "executive",
    description: "Commanding presence for C-level executives",
    descriptionRo: "Prezență impunătoare pentru executivi C-level",
    layout: "single-column",
    colorScheme: {
      primary: "#0c0a09",
      secondary: "#1c1917",
      accent: "#b45309",
      background: "#fafaf9",
      text: "#0c0a09",
      muted: "#78716c",
    },
    atsScore: 95,
    isPremium: true,
    previewImage: "/templates/ceo-suite.png",
    tags: ["executive", "CEO", "leadership", "senior"],
  },
  {
    id: "board-room",
    name: "Board Room",
    nameRo: "Sala de Consiliu",
    category: "executive",
    description: "Prestigious design for board members",
    descriptionRo: "Design prestigios pentru membri ai consiliului",
    layout: "sidebar-right",
    colorScheme: {
      primary: "#14532d",
      secondary: "#166534",
      accent: "#16a34a",
      background: "#f0fdf4",
      text: "#14532d",
      muted: "#86efac",
    },
    atsScore: 94,
    isPremium: true,
    previewImage: "/templates/board-room.png",
    tags: ["board", "director", "senior", "management"],
  },
  {
    id: "senior-partner",
    name: "Senior Partner",
    nameRo: "Partener Senior",
    category: "executive",
    description: "Distinguished layout for senior partners",
    descriptionRo: "Layout distins pentru parteneri senior",
    layout: "two-column",
    colorScheme: {
      primary: "#1e3a8a",
      secondary: "#1e40af",
      accent: "#3b82f6",
      background: "#eff6ff",
      text: "#1e3a8a",
      muted: "#93c5fd",
    },
    atsScore: 93,
    isPremium: true,
    previewImage: "/templates/senior-partner.png",
    tags: ["partner", "senior", "law", "consulting"],
  },
  {
    id: "vp-level",
    name: "VP Level",
    nameRo: "Nivel VP",
    category: "executive",
    description: "Polished design for VP positions",
    descriptionRo: "Design lustruit pentru poziții VP",
    layout: "single-column",
    colorScheme: {
      primary: "#4c1d95",
      secondary: "#5b21b6",
      accent: "#8b5cf6",
      background: "#faf5ff",
      text: "#4c1d95",
      muted: "#c4b5fd",
    },
    atsScore: 96,
    isPremium: true,
    previewImage: "/templates/vp-level.png",
    tags: ["VP", "director", "management", "leadership"],
  },

  // ============================================
  // ACADEMIC TEMPLATES (4)
  // ============================================
  {
    id: "academic-classic",
    name: "Academic Classic",
    nameRo: "Academic Clasic",
    category: "academic",
    description: "Traditional format for researchers",
    descriptionRo: "Format tradițional pentru cercetători",
    layout: "single-column",
    colorScheme: {
      primary: "#1e3a5f",
      secondary: "#2c5282",
      accent: "#4299e1",
      background: "#ffffff",
      text: "#1a202c",
      muted: "#a0aec0",
    },
    atsScore: 99,
    isPremium: false,
    previewImage: "/templates/academic-classic.png",
    tags: ["academic", "research", "professor", "PhD"],
  },
  {
    id: "research-fellow",
    name: "Research Fellow",
    nameRo: "Cercetător",
    category: "academic",
    description: "Detailed layout for publications",
    descriptionRo: "Layout detaliat pentru publicații",
    layout: "single-column",
    colorScheme: {
      primary: "#065f46",
      secondary: "#047857",
      accent: "#10b981",
      background: "#ecfdf5",
      text: "#064e3b",
      muted: "#6ee7b7",
    },
    atsScore: 98,
    isPremium: true,
    previewImage: "/templates/research-fellow.png",
    tags: ["research", "science", "publications", "fellow"],
  },
  {
    id: "professor",
    name: "Professor",
    nameRo: "Profesor",
    category: "academic",
    description: "Comprehensive CV for educators",
    descriptionRo: "CV comprehensiv pentru educatori",
    layout: "two-column",
    colorScheme: {
      primary: "#7c2d12",
      secondary: "#9a3412",
      accent: "#ea580c",
      background: "#fff7ed",
      text: "#7c2d12",
      muted: "#fdba74",
    },
    atsScore: 97,
    isPremium: true,
    previewImage: "/templates/professor.png",
    tags: ["professor", "teacher", "education", "university"],
  },
  {
    id: "phd-candidate",
    name: "PhD Candidate",
    nameRo: "Candidat Doctorat",
    category: "academic",
    description: "Focused layout for doctoral candidates",
    descriptionRo: "Layout focusat pentru candidați la doctorat",
    layout: "single-column",
    colorScheme: {
      primary: "#4338ca",
      secondary: "#4f46e5",
      accent: "#6366f1",
      background: "#eef2ff",
      text: "#3730a3",
      muted: "#a5b4fc",
    },
    atsScore: 98,
    isPremium: false,
    previewImage: "/templates/phd-candidate.png",
    tags: ["PhD", "doctoral", "student", "research"],
  },
];

// Helper functions
export function getTemplatesByCategory(category: string): Template[] {
  return templates.filter((t) => t.category === category);
}

export function getFreeTemplates(): Template[] {
  return templates.filter((t) => !t.isPremium);
}

export function getPremiumTemplates(): Template[] {
  return templates.filter((t) => t.isPremium);
}

export function getTemplateById(id: string): Template | undefined {
  return templates.find((t) => t.id === id);
}

export function searchTemplates(query: string): Template[] {
  const lowerQuery = query.toLowerCase();
  return templates.filter(
    (t) =>
      t.name.toLowerCase().includes(lowerQuery) ||
      t.nameRo.toLowerCase().includes(lowerQuery) ||
      t.tags.some((tag) => tag.toLowerCase().includes(lowerQuery)) ||
      t.category.toLowerCase().includes(lowerQuery)
  );
}
